name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install, build
        uses: withastro/action@15aa0a5a1e067940253e3b259413ab2ae882a740 # v5

      - name: Run lint
        run: pnpm run lint
