name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install, build
        uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6

      - name: Run lint
        run: pnpm run lint
